modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "create_fast_pipes"
version = "${version}"
displayName = "Create: Fast Pipes"
authors = "aruloci"
description = '''
Makes the flow rate of Create's fluid pipes configurable. Server-side only.
'''
logoFile = "assets/create_fast_pipes/icon.png"

[[dependencies.create_fast_pipes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_fast_pipes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_fast_pipes]]
modId = "create"
type = "required"
versionRange = "[6.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "create_fast_pipes.mixins.json"
